version: '3.7'

services:
  openvpn:
    container_name: "openvpn-server"
    build:
      context: ./openvpn
      dockerfile: Dockerfile
    env_file:
        - .env
    volumes:
      - ./openvpn/data/:/etc/openvpn
    restart: always
    ports:
      - "${OPENVPN_PORT}:1194/udp"
  shadowsocks:
    container_name: "shadowsocks-server"
    build:
      context: ./shadowsocks
      dockerfile: Dockerfile
    env_file:
        - .env
    restart: always
    ports:
      - "${SHADOWSOCKS_PORT}:14574/tcp"
      - "${SHADOWSOCKS_PORT}:14574/udp"